spring:
  application:
    name: NettyTest

server:
  port: 8080

netty:
  port: 9090
  enable: true #是否开启netty服务
  overtime: 30 # 超时未响应断开链接 单位秒



# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认1天）
  expireTime: 1440